language: php
php:
  - 7.1
  
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

services:
  - mysql

env:
  -APP_NAME=XTRACT_API
  -APP_ENV=testing
  -DB_USERNAME=root
  -DB_PASSWORD=
  -APP_DEBUG=true
  -APP_LOG_LEVEL=debug
  -CORS_ALLOWED_ORIGINS=
  -APP_URL=
  -APP_SERVER_URL=
  -APP_PATH=
  -DB_CONNECTION=mysql
  -DB_HOST=127.0.0.1
  -DB_PORT=3306
  -DB_DATABASE=test
  -API_LOG_ENABLED=true
  -OAUTH_ENABLED=true

before_install:
  - chmod 777 -R storage
  - composer install
  - composer clear-cache

before_script:
  - unzip tests/xtract_api_test_init_db.zip -d tests
  - mysql -e 'create database test'
  - mysql test < tests/xtract_api_test_init.sql
  - mysql_tzinfo_to_sql /usr/share/zoneinfo/|mysql -u root mysql
  - mysql -e 'SET GLOBAL time_zone = "America/Los_Angeles"'

script: vendor/bin/phpunit --verbose --coverage-clover clover-coverage.xml

notifications:
  slack: xtractsolutions:dlBYjW88746Ur4JzcpEy4DIu
